Feat/logging messages
FinnHuelsbusch/tutorensystem pull request #38
Opened 2022-03-14 10:46 UTC by johannesKnoll

To be done: @tiko2302 Fix errors on displaying info logs in log file

2022-03-14 11:00 UTC, tiko2302 commented on backend/pom.xml
> +			<groupId>org.mariadb.jdbc</groupId>
Soll das wirklich als mariadb in den branch gemerget werden? Die meisten nutzen doch PostgreSQL oder lieg ich da falsch?
Macht es dann nicht mehr Sinn diese Änderung nicht zu mergen?

2022-03-14 18:34 UTC, tiko2302 commented on backend/src/main/java/com/dhbw/tutorsystem/mails/EmailSenderService.java
> +        } else if(mailType == MailType.USER_ADDED_TO_TUTORIAL){
Die Mailtypes scheinen im Enum MailType.java zu fehlen. Werde die ergänzen, damit ich den Fehler mit den Logging Messages korrigieren kann. Kein Änderungsbedarf also.

2022-03-16 10:20 UTC, FinnHuelsbusch requested changes

2022-03-16 10:20 UTC, FinnHuelsbusch commented on backend/src/main/java/com/dhbw/tutorsystem/mails/EmailSenderService.java
> +        String htmlBody = thymeTemplateEngine.process("./Email-Template/E-Mail-Registrierung/Email-Template_Registrierung.html", thymeleafContext);
falscher Branch

2022-03-16 10:20 UTC, FinnHuelsbusch commented on backend/src/test/java/com/dhbw/tutorsystem/TutorsystemApplicationTests.java
> -	void contextLoads() {
falscher branch / nur lokal benötigt

2022-03-16 10:20 UTC, FinnHuelsbusch commented on backend/pom.xml
> +            <artifactId>postgresql</artifactId>
bitte so strukturieren, dass es kein diff ist

2022-03-16 10:20 UTC, FinnHuelsbusch commented on backend/src/main/java/com/dhbw/tutorsystem/security/services/UserDetailsServiceImpl.java
> +            .orElseThrow(() -> {
hier bitte nur orElse und dann da drin trhown, der log hat nix mit dem throw zu tun

2022-03-16 10:47 UTC, FinnHuelsbusch approved these changes, later dismissed

2022-03-16 10:50 UTC, FinnHuelsbusch approved these changes

2022-03-16 10:58 UTC, merged