Feat/mockup data
FinnHuelsbusch/tutorensystem pull request #53
Opened 2022-03-25 12:31 UTC by johannesKnoll

2022-03-26 21:57 UTC, FinnHuelsbusch commented
bitte fixen

2022-04-14 10:04 UTC, FinnHuelsbusch requested changes, later dismissed
Bitte entfernt die Namen und ersetzt sich durch richtige Mock daten. Dat kann man Holey so nicht zeigen und entfernt bitte noch die HTML-Datei

2022-04-14 10:04 UTC, FinnHuelsbusch commented on backend/src/main/java/com/dhbw/tutorsystem/DevDataManager.java
> +        uTutor9.setFirstName("Deez");
Euer ernst ?

2022-04-25 14:30 UTC, johannesKnoll commented on backend/src/main/java/com/dhbw/tutorsystem/DevDataManager.java
> +        uTutor9.setFirstName("Deez");
Welche HTML-Datei meinst du?

2022-04-25 14:34 UTC, FinnHuelsbusch commented on backend/src/main/java/com/dhbw/tutorsystem/mails/Email-Template/Email-Regestrierung/Email-Template_Registrierung.html
> +<title></title>
die hier

2022-04-25 14:34 UTC, FinnHuelsbusch commented on backend/src/main/java/com/dhbw/tutorsystem/mails/Email-Template/Email-Regestrierung/Email-Template_Registrierung.html
> +<title></title>
@johannesKnoll

2022-04-25 14:35 UTC, johannesKnoll commented on backend/src/main/java/com/dhbw/tutorsystem/mails/Email-Template/Email-Regestrierung/Email-Template_Registrierung.html
> +<title></title>
Das hat doch nichts mit den Mockup-Daten zu tun

2022-04-25 14:36 UTC, FinnHuelsbusch commented on backend/src/main/java/com/dhbw/tutorsystem/mails/Email-Template/Email-Regestrierung/Email-Template_Registrierung.html
> +<title></title>
ach ne. Deswegen soll sie ja auch aus dem pr raus....

2022-04-25 14:39 UTC, johannesKnoll commented on backend/src/main/java/com/dhbw/tutorsystem/mails/Email-Template/Email-Regestrierung/Email-Template_Registrierung.html
> +<title></title>
Achso sorry, hab nicht gesehen dass die in dem PR drin war

2022-04-25 15:51 UTC, tiko2302 approved these changes
passt alles soweit ich das sehe

2022-04-25 15:52 UTC, merged